config/routes.rb
InnovationContest::Application.routes.draw do
  resources :users
  resources :ideas
  resources :idea_comments
  resources :idea_files
  resources :idea_likes
  resources :pages
  resources :page_items
  resources :posts

end

app/models/idea_comment.rb
class IdeaComment < ActiveRecord::Base
  attr_accessible :user_id, :idea_id, :content, :published

  #
  # Relations
  #

  # One-to-many relations
  belongs_to :idea
  belongs_to :user


  #
  # Validations
  #

  validates :content, presence: true

end

app/controllers/idea_comments_controller.rb
class IdeaCommentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_idea_comment, only: [:show, :edit, :update, :destroy]
  add_crumb("Idea Comments") { |instance| instance.send :idea_comments_path }

  # GET /idea_comments
  def index
    @idea_comments = IdeaComment.paginate(page: params[:page])
  end

  # GET /idea_comments/1
  def show
    add_crumb @idea_comment.user_id
  end

  # GET /idea_comments/new
  def new
    @idea_comment = IdeaComment.new
    add_crumb "Add a New Idea Comment"
  end

  # GET /idea_comments/1/edit
  def edit
    add_crumb @idea_comment.user_id
  end

  # POST /idea_comments
  def create
    @idea_comment = IdeaComment.new(idea_comment_params)

    if @idea_comment.save
      redirect_to @idea_comment, flash: { success: 'The idea comment was successfully created.' }
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /idea_comments/1
  def update
    if @idea_comment.update(idea_comment_params)
      redirect_to @idea_comment, flash: { success: 'The idea comment was successfully updated.' }
    else
      render action: 'edit'
    end
  end

  # DELETE /idea_comments/1
  def destroy
    @idea_comment.destroy
    redirect_to idea_comments_url, flash: { success: 'The idea comment was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea_comment
      @idea_comment = IdeaComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_comment_params
      params.require(:idea_comment).permit(:user_id, :idea_id, :content, :published)
    end
end

app/views/idea_comments/_form.html.haml
= form_for @idea_comment do |f|

  .row
    .grid12
      = render partial: "partials/form_errors", locals: { object: @idea_comment }

  .row
    .grid2
      = f.label :user_id, class: "required"
    .grid10
      = f.number_field :user_id
  .row
    .grid2
      = f.label :idea_id, class: "required"
    .grid10
      = f.number_field :idea_id
  .row
    .grid2
      = f.label :content, class: "required"
    .grid10
      = f.text_area :content, rows: 4
  .row
    .grid2
      = f.label :published, class: "required"
    .grid10
      = f.check_box :published

  .row
    .grid10.offset2
      = render partial: "partials/form_buttons",
                        locals: { f: f, cancel_path: idea_comments_path, object: @idea_comment }

app/views/idea_comments/edit.html.haml
%h1 Update Idea Comment

= render "form"

app/views/idea_comments/index.html.haml
%section.listing

  %h1 Idea Comments

  .row
    .grid8
      - if can? :create, IdeaComment
        = link_to "Add a Idea Comment", new_idea_comment_path, class: "button secondary"
    .grid2
      %input#search-field{placeholder: "Search", type: "text"}
    .grid2
      = link_to "Search", idea_comments_path, class: "button"

  %table.table-condensed.table-bordered.table-striped
    %thead
      %tr
        %th User
        %th Idea
        %th Content
        %th Published

    %tbody
      - @idea_comments.each do |idea_comment|
        %tr
          %td
            - if can? :update, idea_comment
              = link_to "Edit", edit_idea_comment_path(idea_comment), class: "button"
            = idea_comment.user_id
          %td
            = idea_comment.idea_id
          %td
            = idea_comment.content
          %td
            = t idea_comment.published.class

  = pagination_links(@idea_comments)

app/views/idea_comments/new.html.haml
%h1 Add a Idea Comment

= render "form"

app/views/idea_comments/show.html.haml
%h1 Idea Comment
- if can? :update, @idea_comment
  = link_to "Edit", edit_idea_comment_path(@idea_comment), class: "button"

.row
  .grid2
    %h4 User
  .grid10
    %span= @idea_comment.user_id
.row
  .grid2
    %h4 Idea
  .grid10
    %span= @idea_comment.idea_id
.row
  .grid2
    %h4 Content
  .grid10
    %span= @idea_comment.content
.row
  .grid2
    %h4 Published
  .grid10
    %span= @idea_comment.published