config/routes.rb
InnovationContest::Application.routes.draw do
  resources :users
  resources :ideas
  resources :idea_comments
  resources :idea_files
  resources :idea_likes
  resources :pages
  resources :page_items
  resources :posts

end

app/models/idea_like.rb
class IdeaLike < ActiveRecord::Base
  attr_accessible :idea_id, :user_id

  #
  # Relations
  #

  # One-to-many relations
  belongs_to :idea, :user


  #
  # Validations
  #

  validates :idea, presence: true
  validates :user, presence: true
  validates :user_id, uniqueness: { scope: :idea_id }

end

app/controllers/idea_likes_controller.rb
class IdeaLikesController < ApplicationController
  load_and_authorize_resource
  before_action :set_idea_like, only: [:show, :edit, :update, :destroy]
  add_crumb("Idea Likes") { |instance| instance.send :idea_likes_path }

  # GET /idea_likes
  def index
    @idea_likes = IdeaLike.paginate(page: params[:page])
  end

  # GET /idea_likes/1
  def show
    add_crumb @idea_like.user_id
  end

  # GET /idea_likes/new
  def new
    @idea_like = IdeaLike.new
    add_crumb "Add a New Idea Like"
  end

  # GET /idea_likes/1/edit
  def edit
    add_crumb @idea_like.user_id
  end

  # POST /idea_likes
  def create
    @idea_like = IdeaLike.new(idea_like_params)

    if @idea_like.save
      redirect_to @idea_like, flash: { success: 'The idea like was successfully created.' }
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /idea_likes/1
  def update
    if @idea_like.update(idea_like_params)
      redirect_to @idea_like, flash: { success: 'The idea like was successfully updated.' }
    else
      render action: 'edit'
    end
  end

  # DELETE /idea_likes/1
  def destroy
    @idea_like.destroy
    redirect_to idea_likes_url, flash: { success: 'The idea like was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea_like
      @idea_like = IdeaLike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_like_params
      params.require(:idea_like).permit(:user_id, :idea_id)
    end
end

app/views/idea_likes/_form.html.haml
= form_for @idea_like do |f|

  .row
    .grid12
      = render partial: "partials/form_errors", locals: { object: @idea_like }

  .row
    .grid2
      = f.label :user_id, class: "required"
    .grid10
      = f.number_field :user_id
  .row
    .grid2
      = f.label :idea_id, class: "required"
    .grid10
      = f.number_field :idea_id

  .row
    .grid10.offset2
      = render partial: "partials/form_buttons",
                        locals: { f: f, cancel_path: idea_likes_path, object: @idea_like }

app/views/idea_likes/edit.html.haml
%h1 Update Idea Like

= render "form"

app/views/idea_likes/index.html.haml
%section.listing

  %h1 Idea Likes

  .row
    .grid8
      - if can? :create, IdeaLike
        = link_to "Add a Idea Like", new_idea_like_path, class: "button secondary"
    .grid2
      %input#search-field{placeholder: "Search", type: "text"}
    .grid2
      = link_to "Search", idea_likes_path, class: "button"

  %table.table-condensed.table-bordered.table-striped
    %thead
      %tr
        %th User
        %th Idea

    %tbody
      - @idea_likes.each do |idea_like|
        %tr
          %td
            - if can? :update, idea_like
              = link_to "Edit", edit_idea_like_path(idea_like), class: "button"
            = idea_like.user_id
          %td
            = idea_like.idea_id

  = pagination_links(@idea_likes)

app/views/idea_likes/new.html.haml
%h1 Add a Idea Like

= render "form"

app/views/idea_likes/show.html.haml
%h1 Idea Like
- if can? :update, @idea_like
  = link_to "Edit", edit_idea_like_path(@idea_like), class: "button"

.row
  .grid2
    %h4 User
  .grid10
    %span= @idea_like.user_id
.row
  .grid2
    %h4 Idea
  .grid10
    %span= @idea_like.idea_id