config/routes.rb
InnovationContest::Application.routes.draw do
  resources :users
  resources :ideas
  resources :idea_comments
  resources :idea_files
  resources :idea_likes
  resources :pages
  resources :page_items
  resources :posts

end

app/models/idea_file.rb
class IdeaFile < ActiveRecord::Base
  attr_accessible :idea_id, :user_id, :file, :published


  #
  # Relations
  #

  # One-to-many relations
  belongs_to :idea
  belongs_to :user


  #
  # Validations
  #

  validates :idea, :file, :user presence: true

end

app/controllers/idea_files_controller.rb
class IdeaFilesController < ApplicationController
  load_and_authorize_resource
  before_action :set_idea_file, only: [:show, :edit, :update, :destroy]
  add_crumb("Idea Files") { |instance| instance.send :idea_files_path }

  # GET /idea_files
  def index
    @idea_files = IdeaFile.paginate(page: params[:page])
  end

  # GET /idea_files/1
  def show
    add_crumb @idea_file.idea_id
  end

  # GET /idea_files/new
  def new
    @idea_file = IdeaFile.new
    add_crumb "Add a New Idea File"
  end

  # GET /idea_files/1/edit
  def edit
    add_crumb @idea_file.idea_id
  end

  # POST /idea_files
  def create
    @idea_file = IdeaFile.new(idea_file_params)

    if @idea_file.save
      redirect_to @idea_file, flash: { success: 'The idea file was successfully created.' }
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /idea_files/1
  def update
    if @idea_file.update(idea_file_params)
      redirect_to @idea_file, flash: { success: 'The idea file was successfully updated.' }
    else
      render action: 'edit'
    end
  end

  # DELETE /idea_files/1
  def destroy
    @idea_file.destroy
    redirect_to idea_files_url, flash: { success: 'The idea file was successfully deleted.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea_file
      @idea_file = IdeaFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_file_params
      params.require(:idea_file).permit(:idea_id, :file, :published)
    end
end

app/views/idea_files/_form.html.haml
= form_for @idea_file do |f|

  .row
    .grid12
      = render partial: "partials/form_errors", locals: { object: @idea_file }

  .row
    .grid2
      = f.label :idea_id, class: "required"
    .grid10
      = f.number_field :idea_id
  .row
    .grid2
      = f.label :file, class: "required"
    .grid10
      = f.text_field :file
  .row
    .grid2
      = f.label :published, class: "required"
    .grid10
      = f.check_box :published

  .row
    .grid10.offset2
      = render partial: "partials/form_buttons",
                        locals: { f: f, cancel_path: idea_files_path, object: @idea_file }

app/views/idea_files/edit.html.haml
%h1 Update Idea File

= render "form"

app/views/idea_files/index.html.haml
%section.listing

  %h1 Idea Files

  .row
    .grid8
      - if can? :create, IdeaFile
        = link_to "Add a Idea File", new_idea_file_path, class: "button secondary"
    .grid2
      %input#search-field{placeholder: "Search", type: "text"}
    .grid2
      = link_to "Search", idea_files_path, class: "button"

  %table.table-condensed.table-bordered.table-striped
    %thead
      %tr
        %th Idea
        %th File
        %th Published

    %tbody
      - @idea_files.each do |idea_file|
        %tr
          %td
            - if can? :update, idea_file
              = link_to "Edit", edit_idea_file_path(idea_file), class: "button"
            = idea_file.idea_id
          %td
            = idea_file.file
          %td
            = t idea_file.published.class

  = pagination_links(@idea_files)

app/views/idea_files/new.html.haml
%h1 Add a Idea File

= render "form"

app/views/idea_files/show.html.haml
%h1 Idea File
- if can? :update, @idea_file
  = link_to "Edit", edit_idea_file_path(@idea_file), class: "button"

.row
  .grid2
    %h4 Idea
  .grid10
    %span= @idea_file.idea_id
.row
  .grid2
    %h4 File
  .grid10
    %span= @idea_file.file
.row
  .grid2
    %h4 Published
  .grid10
    %span= @idea_file.published